<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Archivo\**" />
    <EmbeddedResource Remove="Archivo\**" />
    <None Remove="Archivo\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="_S3Uploader.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.3" />
    <PackageReference Include="FFMpegCore" Version="5.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.9" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
    <PackageReference Include="Xabe.FFmpeg" Version="6.0.2" />
    <PackageReference Include="Xabe.FFmpeg.Downloader" Version="6.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dtos\Dtos.csproj" />
  </ItemGroup>

</Project>
